# JVM
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# Android
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
android.strictManifestPackageUsage=false

# Gradle performance
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# REMOVED: org.gradle.configuration-cache=true  ? this was causing the error